version: '3.7'
services:
  postgres:
    container_name: nodejs_postgresql_db
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodejs_mentoring
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./temp/data:/var/lib/postgresql/data

  adminer:
    container_name: nodejs_adminer
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 4000:8080
